name: Spring Boot CI Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: maven:3.9-eclipse-temurin-17

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Build and Package Spring Boot App 
      working-directory: User
      run: mvn clean package
